/* The following code was generated by JFlex 1.4.4 on 09.05.15 2:18 */

package org.mustbe.consulo.unity3d.shaderlab.lang.lexer;

import org.mustbe.consulo.unity3d.shaderlab.lang.psi.ShaderLabTokens;
import com.intellij.lexer.LexerBase;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.4
 * on 09.05.15 2:18 from the specification file
 * <tt>R:/_github.com/consulo/consulo-unity3d/shaderlab/src/org/mustbe/consulo/unity3d/shaderlab/lang/lexer/ShaderLabLexer.flex</tt>
 */
public class _ShaderLabLexer extends LexerBase {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int SHADERSCRIPT = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\11\1\2\1\4\1\0\1\2\1\4\16\11\4\0\1\2\1\0"+
    "\1\6\1\0\1\10\3\0\1\41\1\42\1\5\1\12\1\45\1\12"+
    "\1\13\1\3\12\1\3\0\1\46\3\0\1\16\1\30\1\31\1\17"+
    "\1\20\1\26\1\34\1\15\1\25\1\10\1\32\1\27\1\36\1\35"+
    "\1\23\1\22\1\10\1\21\1\14\1\24\1\33\5\10\1\43\1\7"+
    "\1\44\1\0\1\10\1\0\1\16\1\30\1\31\1\17\1\20\1\26"+
    "\1\34\1\15\1\25\1\10\1\32\1\27\1\36\1\35\1\23\1\22"+
    "\1\10\1\21\1\14\1\24\1\33\5\10\1\37\1\0\1\40\1\0"+
    "\41\11\2\0\4\10\4\0\1\10\2\0\1\11\7\0\1\10\4\0"+
    "\1\10\5\0\27\10\1\0\37\10\1\0\u013f\10\31\0\162\10\4\0"+
    "\14\10\16\0\5\10\11\0\1\10\21\0\130\11\5\0\23\11\12\0"+
    "\1\10\13\0\1\10\1\0\3\10\1\0\1\10\1\0\24\10\1\0"+
    "\54\10\1\0\46\10\1\0\5\10\4\0\202\10\1\0\4\11\3\0"+
    "\105\10\1\0\46\10\2\0\2\10\6\0\20\10\41\0\46\10\2\0"+
    "\1\10\7\0\47\10\11\0\21\11\1\0\27\11\1\0\3\11\1\0"+
    "\1\11\1\0\2\11\1\0\1\11\13\0\33\10\5\0\3\10\15\0"+
    "\4\11\14\0\6\11\13\0\32\10\5\0\13\10\16\11\7\0\12\11"+
    "\4\0\2\10\1\11\143\10\1\0\1\10\10\11\1\0\6\11\2\10"+
    "\2\11\1\0\4\11\2\10\12\11\3\10\2\0\1\10\17\0\1\11"+
    "\1\10\1\11\36\10\33\11\2\0\3\10\60\0\46\10\13\11\1\10"+
    "\u014f\0\3\11\66\10\2\0\1\11\1\10\20\11\2\0\1\10\4\11"+
    "\3\0\12\10\2\11\2\0\12\11\21\0\3\11\1\0\10\10\2\0"+
    "\2\10\2\0\26\10\1\0\7\10\1\0\1\10\3\0\4\10\2\0"+
    "\1\11\1\10\7\11\2\0\2\11\2\0\3\11\11\0\1\11\4\0"+
    "\2\10\1\0\3\10\2\11\2\0\12\11\4\10\15\0\3\11\1\0"+
    "\6\10\4\0\2\10\2\0\26\10\1\0\7\10\1\0\2\10\1\0"+
    "\2\10\1\0\2\10\2\0\1\11\1\0\5\11\4\0\2\11\2\0"+
    "\3\11\13\0\4\10\1\0\1\10\7\0\14\11\3\10\14\0\3\11"+
    "\1\0\11\10\1\0\3\10\1\0\26\10\1\0\7\10\1\0\2\10"+
    "\1\0\5\10\2\0\1\11\1\10\10\11\1\0\3\11\1\0\3\11"+
    "\2\0\1\10\17\0\2\10\2\11\2\0\12\11\1\0\1\10\17\0"+
    "\3\11\1\0\10\10\2\0\2\10\2\0\26\10\1\0\7\10\1\0"+
    "\2\10\1\0\5\10\2\0\1\11\1\10\6\11\3\0\2\11\2\0"+
    "\3\11\10\0\2\11\4\0\2\10\1\0\3\10\4\0\12\11\1\0"+
    "\1\10\20\0\1\11\1\10\1\0\6\10\3\0\3\10\1\0\4\10"+
    "\3\0\2\10\1\0\1\10\1\0\2\10\3\0\2\10\3\0\3\10"+
    "\3\0\10\10\1\0\3\10\4\0\5\11\3\0\3\11\1\0\4\11"+
    "\11\0\1\11\17\0\11\11\11\0\1\10\7\0\3\11\1\0\10\10"+
    "\1\0\3\10\1\0\27\10\1\0\12\10\1\0\5\10\4\0\7\11"+
    "\1\0\3\11\1\0\4\11\7\0\2\11\11\0\2\10\4\0\12\11"+
    "\22\0\2\11\1\0\10\10\1\0\3\10\1\0\27\10\1\0\12\10"+
    "\1\0\5\10\2\0\1\11\1\10\7\11\1\0\3\11\1\0\4\11"+
    "\7\0\2\11\7\0\1\10\1\0\2\10\4\0\12\11\22\0\2\11"+
    "\1\0\10\10\1\0\3\10\1\0\27\10\1\0\20\10\4\0\6\11"+
    "\2\0\3\11\1\0\4\11\11\0\1\11\10\0\2\10\4\0\12\11"+
    "\22\0\2\11\1\0\22\10\3\0\30\10\1\0\11\10\1\0\1\10"+
    "\2\0\7\10\3\0\1\11\4\0\6\11\1\0\1\11\1\0\10\11"+
    "\22\0\2\11\15\0\60\10\1\11\2\10\7\11\4\0\10\10\10\11"+
    "\1\0\12\11\47\0\2\10\1\0\1\10\2\0\2\10\1\0\1\10"+
    "\2\0\1\10\6\0\4\10\1\0\7\10\1\0\3\10\1\0\1\10"+
    "\1\0\1\10\2\0\2\10\1\0\4\10\1\11\2\10\6\11\1\0"+
    "\2\11\1\10\2\0\5\10\1\0\1\10\1\0\6\11\2\0\12\11"+
    "\2\0\2\10\42\0\1\10\27\0\2\11\6\0\12\11\13\0\1\11"+
    "\1\0\1\11\1\0\1\11\4\0\2\11\10\10\1\0\42\10\6\0"+
    "\24\11\1\0\2\11\4\10\4\0\10\11\1\0\44\11\11\0\1\11"+
    "\71\0\42\10\1\0\5\10\1\0\2\10\1\0\7\11\3\0\4\11"+
    "\6\0\12\11\6\0\6\10\4\11\106\0\46\10\12\0\51\10\7\0"+
    "\132\10\5\0\104\10\5\0\122\10\6\0\7\10\1\0\77\10\1\0"+
    "\1\10\1\0\4\10\2\0\7\10\1\0\1\10\1\0\4\10\2\0"+
    "\47\10\1\0\1\10\1\0\4\10\2\0\37\10\1\0\1\10\1\0"+
    "\4\10\2\0\7\10\1\0\1\10\1\0\4\10\2\0\7\10\1\0"+
    "\7\10\1\0\27\10\1\0\37\10\1\0\1\10\1\0\4\10\2\0"+
    "\7\10\1\0\47\10\1\0\23\10\16\0\11\11\56\0\125\10\14\0"+
    "\u026c\10\2\0\10\10\12\0\32\10\5\0\113\10\3\0\3\10\17\0"+
    "\15\10\1\0\4\10\3\11\13\0\22\10\3\11\13\0\22\10\2\11"+
    "\14\0\15\10\1\0\3\10\1\0\2\11\14\0\64\10\40\11\3\0"+
    "\1\10\3\0\2\10\1\11\2\0\12\11\41\0\3\11\2\0\12\11"+
    "\6\0\130\10\10\0\51\10\1\11\126\0\35\10\3\0\14\11\4\0"+
    "\14\11\12\0\12\11\36\10\2\0\5\10\u038b\0\154\10\224\0\234\10"+
    "\4\0\132\10\6\0\26\10\2\0\6\10\2\0\46\10\2\0\6\10"+
    "\2\0\10\10\1\0\1\10\1\0\1\10\1\0\1\10\1\0\37\10"+
    "\2\0\65\10\1\0\7\10\1\0\1\10\3\0\3\10\1\0\7\10"+
    "\3\0\4\10\2\0\6\10\4\0\15\10\5\0\3\10\1\0\7\10"+
    "\17\0\4\11\32\0\5\11\20\0\2\10\23\0\1\10\13\0\4\11"+
    "\6\0\6\11\1\0\1\10\15\0\1\10\40\0\22\10\36\0\15\11"+
    "\4\0\1\11\3\0\6\11\27\0\1\10\4\0\1\10\2\0\12\10"+
    "\1\0\1\10\3\0\5\10\6\0\1\10\1\0\1\10\1\0\1\10"+
    "\1\0\4\10\1\0\3\10\1\0\7\10\3\0\3\10\5\0\5\10"+
    "\26\0\44\10\u0e81\0\3\10\31\0\11\10\6\11\1\0\5\10\2\0"+
    "\5\10\4\0\126\10\2\0\2\11\2\0\3\10\1\0\137\10\5\0"+
    "\50\10\4\0\136\10\21\0\30\10\70\0\20\10\u0200\0\u19b6\10\112\0"+
    "\u51a6\10\132\0\u048d\10\u0773\0\u2ba4\10\u215c\0\u012e\10\2\0\73\10\225\0"+
    "\7\10\14\0\5\10\5\0\1\10\1\11\12\10\1\0\15\10\1\0"+
    "\5\10\1\0\1\10\1\0\2\10\1\0\2\10\1\0\154\10\41\0"+
    "\u016b\10\22\0\100\10\2\0\66\10\50\0\15\10\3\0\20\11\20\0"+
    "\4\11\17\0\2\10\30\0\3\10\31\0\1\10\6\0\5\10\1\0"+
    "\207\10\2\0\1\11\4\0\1\10\13\0\12\11\7\0\32\10\4\0"+
    "\1\10\1\0\32\10\12\0\132\10\3\0\6\10\2\0\6\10\2\0"+
    "\6\10\2\0\3\10\3\0\2\10\3\0\2\10\22\0\3\11\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\1\1\4\1\5\2\1"+
    "\6\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\2\16\1\5\1\0\1\17\1\20\2\4\1\2"+
    "\10\5\2\0\11\5\1\0\1\20\3\5\1\21\1\5"+
    "\1\22\3\5\1\0\2\5\1\23\4\5\1\24\1\25"+
    "\14\5\1\26\2\5\1\27\1\5\1\30\1\31\1\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\234\0\303\0\352\0\u0111"+
    "\0\u0138\0\u015f\0\u0186\0\u01ad\0\u01d4\0\u01fb\0\u0222\0\u0249"+
    "\0\116\0\116\0\116\0\116\0\116\0\116\0\116\0\116"+
    "\0\116\0\u0270\0\116\0\u015f\0\u0297\0\u02be\0\116\0\u02e5"+
    "\0\u030c\0\u0333\0\u035a\0\u0381\0\u03a8\0\u03cf\0\u03f6\0\u041d"+
    "\0\u0444\0\u046b\0\u0492\0\u04b9\0\u04e0\0\u0507\0\u052e\0\u0555"+
    "\0\u057c\0\u05a3\0\u05ca\0\u05f1\0\u0618\0\116\0\u063f\0\u0666"+
    "\0\u068d\0\u0111\0\u06b4\0\u0111\0\u06db\0\u0702\0\u0729\0\u0750"+
    "\0\u0777\0\u079e\0\u0111\0\u07c5\0\u07ec\0\u0813\0\u083a\0\116"+
    "\0\u0111\0\u0861\0\u0888\0\u08af\0\u08d6\0\u08fd\0\u0924\0\u094b"+
    "\0\u0972\0\u0999\0\u09c0\0\u09e7\0\u0a0e\0\u0111\0\u0a35\0\u0a5c"+
    "\0\u0111\0\u0a83\0\u0111\0\u0111\0\u0111";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\5\1\3\1\7\1\3"+
    "\1\10\1\3\1\11\1\12\1\13\3\10\1\14\1\10"+
    "\1\15\1\10\1\16\1\10\1\17\2\10\1\20\5\10"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\20\31\1\32\26\31\50\0\1\4\6\0\1\33\2\0"+
    "\1\34\23\33\12\0\1\5\1\0\1\5\45\0\1\35"+
    "\1\0\1\36\41\0\4\7\1\0\1\7\1\37\1\40"+
    "\37\7\1\0\1\10\6\0\2\10\2\0\23\10\11\0"+
    "\1\4\11\0\1\34\34\0\1\41\46\0\1\10\6\0"+
    "\2\10\2\0\1\10\1\42\15\10\1\43\3\10\11\0"+
    "\1\10\6\0\2\10\2\0\21\10\1\44\1\10\11\0"+
    "\1\10\6\0\2\10\2\0\2\10\1\45\2\10\1\46"+
    "\15\10\11\0\1\10\6\0\2\10\2\0\2\10\1\47"+
    "\20\10\11\0\1\10\6\0\2\10\2\0\2\10\1\50"+
    "\20\10\11\0\1\10\6\0\2\10\2\0\20\10\1\51"+
    "\2\10\45\0\1\52\11\0\4\35\1\0\42\35\5\36"+
    "\1\53\41\36\4\7\1\0\42\7\1\0\1\41\6\0"+
    "\1\33\3\0\23\33\11\0\1\10\6\0\2\10\2\0"+
    "\2\10\1\54\20\10\11\0\1\10\6\0\2\10\2\0"+
    "\14\10\1\55\6\10\11\0\1\10\6\0\2\10\2\0"+
    "\3\10\1\56\17\10\11\0\1\10\6\0\2\10\2\0"+
    "\1\57\22\10\11\0\1\10\6\0\2\10\2\0\7\10"+
    "\1\60\13\10\11\0\1\10\6\0\2\10\2\0\20\10"+
    "\1\61\2\10\11\0\1\10\6\0\2\10\2\0\13\10"+
    "\1\62\7\10\11\0\1\10\6\0\2\10\2\0\6\10"+
    "\1\63\2\10\1\64\11\10\27\0\1\65\27\0\3\36"+
    "\1\66\1\36\1\53\41\36\1\0\1\10\6\0\2\10"+
    "\2\0\3\10\1\67\17\10\11\0\1\10\6\0\2\10"+
    "\2\0\1\70\22\10\11\0\1\10\6\0\2\10\2\0"+
    "\15\10\1\71\5\10\11\0\1\10\6\0\2\10\2\0"+
    "\1\72\22\10\11\0\1\10\6\0\2\10\2\0\6\10"+
    "\1\73\14\10\11\0\1\10\6\0\2\10\2\0\1\74"+
    "\22\10\11\0\1\10\6\0\2\10\2\0\13\10\1\75"+
    "\7\10\11\0\1\10\6\0\2\10\2\0\5\10\1\76"+
    "\15\10\11\0\1\10\6\0\2\10\2\0\21\10\1\77"+
    "\1\10\41\0\1\100\16\0\1\10\6\0\2\10\2\0"+
    "\4\10\1\101\16\10\11\0\1\10\6\0\2\10\2\0"+
    "\1\10\1\102\21\10\11\0\1\10\6\0\2\10\2\0"+
    "\20\10\1\103\2\10\11\0\1\10\6\0\2\10\2\0"+
    "\4\10\1\104\16\10\11\0\1\10\6\0\2\10\2\0"+
    "\14\10\1\105\6\10\11\0\1\10\6\0\2\10\2\0"+
    "\7\10\1\106\13\10\11\0\1\10\6\0\2\10\2\0"+
    "\15\10\1\107\5\10\44\0\1\110\13\0\1\10\6\0"+
    "\2\10\2\0\5\10\1\111\15\10\11\0\1\10\6\0"+
    "\2\10\2\0\2\10\1\112\20\10\11\0\1\10\6\0"+
    "\2\10\2\0\5\10\1\113\15\10\11\0\1\10\6\0"+
    "\2\10\2\0\2\10\1\114\20\10\11\0\1\10\6\0"+
    "\2\10\2\0\20\10\1\115\2\10\11\0\1\10\6\0"+
    "\2\10\2\0\13\10\1\116\7\10\11\0\1\10\6\0"+
    "\2\10\2\0\3\10\1\117\17\10\11\0\1\10\6\0"+
    "\2\10\2\0\10\10\1\120\12\10\11\0\1\10\6\0"+
    "\2\10\2\0\15\10\1\121\5\10\11\0\1\10\6\0"+
    "\2\10\2\0\5\10\1\122\15\10\11\0\1\10\6\0"+
    "\2\10\2\0\17\10\1\123\3\10\11\0\1\10\6\0"+
    "\2\10\2\0\4\10\1\124\16\10\11\0\1\10\6\0"+
    "\2\10\2\0\11\10\1\125\11\10\11\0\1\10\6\0"+
    "\2\10\2\0\16\10\1\126\4\10\11\0\1\10\6\0"+
    "\2\10\2\0\2\10\1\127\20\10\11\0\1\10\6\0"+
    "\2\10\2\0\3\10\1\130\17\10\11\0\1\10\6\0"+
    "\2\10\2\0\5\10\1\131\15\10\11\0\1\10\6\0"+
    "\2\10\2\0\4\10\1\132\16\10\11\0\1\10\6\0"+
    "\2\10\2\0\22\10\1\133\11\0\1\10\6\0\2\10"+
    "\2\0\4\10\1\134\16\10\11\0\1\10\6\0\2\10"+
    "\2\0\1\135\22\10\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2730];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\15\1\11\11\1\1\1\11\1\0\2\1"+
    "\1\11\12\1\2\0\11\1\1\0\1\11\11\1\1\0"+
    "\7\1\1\11\25\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  private IElementType myTokenType;
  private int myState;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;



  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1780) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  @Override
  public IElementType getTokenType() {
    if (myTokenType == null) locateToken();
    return myTokenType;
  }

  @Override
  public final int getTokenStart(){
    if (myTokenType == null) locateToken();
    return zzStartRead;
  }

  @Override
  public final int getTokenEnd(){
    if (myTokenType == null) locateToken();
    return getTokenStart() + yylength();
  }

  @Override
  public void advance() {
    if (myTokenType == null) locateToken();
    myTokenType = null;
  }

  @Override
  public int getState() {
    if (myTokenType == null) locateToken();
    return myState;
  }

  @Override
  public void start(final CharSequence buffer, int startOffset, int endOffset, final int initialState) {
    reset(buffer, startOffset, endOffset, initialState);
    myTokenType = null;
  }

   @Override
   public CharSequence getBufferSequence() {
     return zzBuffer;
   }

   @Override
   public int getBufferEnd() {
     return zzEndRead;
   }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
    myTokenType = null;
  }

   private void locateToken() {
     if (myTokenType != null) return;
     try {
       myState = yystate();
       myTokenType = advanceImpl();
     }
     catch (java.io.IOException e) { /*Can't happen*/ }
     catch (Error e) {
       // add lexer class name to the error
       final Error error = new Error(getClass().getName() + ": " + e.getMessage());
       error.setStackTrace(e.getStackTrace());
       throw error;
     }
   }

   /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advanceImpl() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 9: 
          { return ShaderLabTokens.RPAR;
          }
        case 27: break;
        case 24: 
          { yybegin(SHADERSCRIPT); return ShaderLabTokens.CGPROGRAM_KEYWORD;
          }
        case 28: break;
        case 15: 
          { return ShaderLabTokens.LINE_COMMENT;
          }
        case 29: break;
        case 21: 
          { return ShaderLabTokens.SHADER_KEYWORD;
          }
        case 30: break;
        case 10: 
          { return ShaderLabTokens.LBRACKET;
          }
        case 31: break;
        case 13: 
          { return ShaderLabTokens.EQ;
          }
        case 32: break;
        case 17: 
          { return ShaderLabTokens.PASS_KEYWORD;
          }
        case 33: break;
        case 16: 
          { return ShaderLabTokens.BLOCK_COMMENT;
          }
        case 34: break;
        case 8: 
          { return ShaderLabTokens.LPAR;
          }
        case 35: break;
        case 20: 
          { yybegin(YYINITIAL); yypushback(5);
          }
        case 36: break;
        case 6: 
          { return ShaderLabTokens.LBRACE;
          }
        case 37: break;
        case 2: 
          { return ShaderLabTokens.INTEGER_LITERAL;
          }
        case 38: break;
        case 3: 
          { return ShaderLabTokens.WHITE_SPACE;
          }
        case 39: break;
        case 7: 
          { return ShaderLabTokens.RBRACE;
          }
        case 40: break;
        case 22: 
          { return ShaderLabTokens.FALLBACK_KEYWORD;
          }
        case 41: break;
        case 11: 
          { return ShaderLabTokens.RBRACKET;
          }
        case 42: break;
        case 14: 
          { return ShaderLabTokens.SHADERSCRIPT;
          }
        case 43: break;
        case 12: 
          { return ShaderLabTokens.COMMA;
          }
        case 44: break;
        case 26: 
          { return ShaderLabTokens.PROPERTIES_KEYWORD;
          }
        case 45: break;
        case 18: 
          { return ShaderLabTokens.TAGS_KEYWORD;
          }
        case 46: break;
        case 19: 
          { return ShaderLabTokens.ENDCG_KEYWORD;
          }
        case 47: break;
        case 25: 
          { yybegin(SHADERSCRIPT); return ShaderLabTokens.CGINCLUDE_KEYWORD;
          }
        case 48: break;
        case 5: 
          { return ShaderLabTokens.IDENTIFIER;
          }
        case 49: break;
        case 1: 
          { return ShaderLabTokens.BAD_CHARACTER;
          }
        case 50: break;
        case 23: 
          { return ShaderLabTokens.SUBSHADER_KEYWORD;
          }
        case 51: break;
        case 4: 
          { return ShaderLabTokens.STRING_LITERAL;
          }
        case 52: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
